/**
 * mock/theme/page.tsx — Design system token catalog
 *
 * Purpose: mood-board for tokens. Not a real UI page.
 * Shows every color, size, radius, shadow, and gradient defined in globals.css.
 * Generated by /design-system — update when tokens change.
 */
export default function ThemePage() {
  return (
    <div className="mx-auto max-w-page space-y-12 px-4 py-12">
      <h1 className="text-heading font-semibold">Design Token Catalog</h1>

      {/* Colors */}
      <section className="space-y-4">
        <h2 className="text-body font-semibold uppercase tracking-widest text-muted-foreground">
          Colors
        </h2>
        <div className="grid grid-cols-4 gap-3">
          {[
            { label: "background", cls: "bg-background border" },
            { label: "card", cls: "bg-card border" },
            { label: "primary", cls: "bg-primary" },
            { label: "muted", cls: "bg-muted" },
            { label: "border", cls: "bg-border" },
            { label: "destructive", cls: "bg-destructive" },
          ].map(({ label, cls }) => (
            <div key={label} className="space-y-2">
              <div className={`h-16 rounded-input ${cls}`} />
              <p className="text-small text-muted-foreground">{label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Typography */}
      <section className="space-y-4">
        <h2 className="text-body font-semibold uppercase tracking-widest text-muted-foreground">
          Typography
        </h2>
        <div className="space-y-3 rounded-card border border-border/60 bg-card p-6">
          <p className="text-heading font-semibold">Heading — 24px semibold</p>
          <p className="text-body">Body — 16px normal. The quick brown fox.</p>
          <p className="text-small text-muted-foreground">Small — 12px. Captions, badges, helper text.</p>
        </div>
      </section>

      {/* Radii */}
      <section className="space-y-4">
        <h2 className="text-body font-semibold uppercase tracking-widest text-muted-foreground">
          Radii
        </h2>
        <div className="flex gap-4">
          {[
            { label: "card (24px)", cls: "rounded-card" },
            { label: "input (12px)", cls: "rounded-input" },
            { label: "button (pill)", cls: "rounded-button" },
          ].map(({ label, cls }) => (
            <div key={label} className="space-y-2 text-center">
              <div className={`h-16 w-24 bg-primary/20 border border-primary/40 ${cls}`} />
              <p className="text-small text-muted-foreground">{label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Elevation */}
      <section className="space-y-4">
        <h2 className="text-body font-semibold uppercase tracking-widest text-muted-foreground">
          Elevation
        </h2>
        <div className="flex gap-6">
          {[
            { label: "shadow-card (none)", cls: "shadow-card" },
            { label: "shadow-elevated", cls: "shadow-elevated" },
            { label: "shadow-overlay", cls: "shadow-overlay" },
          ].map(({ label, cls }) => (
            <div
              key={label}
              className={`flex h-20 w-36 items-center justify-center rounded-card bg-card ${cls}`}
            >
              <p className="text-small text-muted-foreground text-center">{label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Gradient */}
      <section className="space-y-4">
        <h2 className="text-body font-semibold uppercase tracking-widest text-muted-foreground">
          CTA Gradient
        </h2>
        <div className="cta-gradient h-20 rounded-card" />
      </section>
    </div>
  );
}
